### PR TITLE
Sync. 

### PR DESCRIPTION
**Pull request by Chapoly1305**

### CODE REVIEW

**Comment by Systm21** [comment]
Hey, please open your issue's on this repo. There are Problems with your [web_service.py](https://github.com/Chapoly1305/FindMy/blob/main/web_service.py)

**Comment by Chapoly1305** [comment]
@Systm21 thanks for the comment, could you elaborate on the issue you ran into? It would be great if you could provide details on recreating the issue, I will have a look later today

**Comment by Systm21** [comment]
i dont want to take over this PR, so i asked for opening your Issues section. I would open it then.

I dont know how to use it and i think the python3 header is missing...

**Comment by Chapoly1305** [comment]
@Systm21 Great idea, I have setup both issues and discussions sessions, feel free to raise them.

**Pull request merged**
